config/routes.rb
Rails.application.routes.draw do
root 'posts#index'

resources :posts do 
  resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :text, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    post = Post.find params[:post_id]
    post.comments.create(params[:comment].permit(:text))

    redirect_to post_path(post)
  end

  def update

  end

  def edit
  end

  def delete
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :text))
    if @post.save
      redirect_to posts_path
    else render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.new params[:post].permit(:title, :text)
    if @post.save
      redirect_to post_path(@post)
    else render 'show'
    end
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<!-- <h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p> -->

<%= form_for [@post, @comment] do |form| %>
  
  <%= form.label :text %>
  <%= form.text_field :text %>

  <%= form.submit 'Send your comment' %>

<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D4TddCapybaraBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav>
    <li> <%= link_to 'All posts', 'post_path' %> </li>
    <li> <%= link_to 'Create post', new_post_path %> </li>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
<!-- <h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p> -->

<%= form_for @post do |form| %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text %>
  <%= form.text_field :text %>

  <%= form.submit 'Submit' %>

<% end %>

app/views/posts/index.html.erb
<!-- <h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p> -->

<h3>All my posts so far</h3>
<ul>
<% @posts.each do |post| %>
  <li> <%= link_to post.title, post_path(post) %> </li>
<% end %>
</ul>

app/views/posts/new.html.erb
<!-- <h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p> -->

<%= form_for @post do |form| %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text %>
  <%= form.text_field :text %>

  <%= form.submit 'Submit' %>

<% end %>

app/views/posts/show.html.erb
<!-- <h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p> -->

<h3> <%= @post.title %> </h3>
<p> <%= link_to 'Edit post', edit_post_path %> </p>
<p> <%= link_to 'Add comment', new_post_comment_path(@post) %> </p>
<p> <%= @post.text %> </p>

<h5> <%= pluralize(@post.comments.length, 'comment') %> so far</h5>
<% @post.comments.each do |comment| %>
<p> <%= time_ago_in_words(Time.now) %></p>
<p> <%= comment.text  %></p>
<% end %>